FROM node:18-slim AS build
WORKDIR /app
COPY aerosurrogate_front/package.json ./package.json
COPY aerosurrogate_front/package-lock.json ./package-lock.json
RUN npm install --legacy-peer-deps
COPY aerosurrogate_front ./
RUN CI=false npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
